comment:
  layout: "header, diff, flags, components, files, footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: auto
        threshold: 0%
        informational: false
    patch:
      default:
        target: auto
        threshold: 0%
        informational: false

ignore:
  - "tests/"
  - "**/__init__.py"
